### ISSUE TITLE
BUG: 单层结构输出数据有误

### ISSUE THREAD

**Issue by Lucareful** [runningzyp/GoStruct2Table#1]
## 问题
hi cai, 我在尝试使用的时候发现一个问题，单层的结构并没有正确的输出，运行 TestParse 用例。
![image](https://user-images.githubusercontent.com/34530552/155261828-4ecc0473-5d12-40f0-9e9a-c0837ececcce.png)

## 排查问题（fix：建议）
![image](https://user-images.githubusercontent.com/34530552/155261951-925a9947-0dc5-438e-964f-50ed8f8b1099.png)

### 增加了一个判断（暂时的） 正常工作
![image](https://user-images.githubusercontent.com/34530552/155262016-36244061-7e52-47a4-8055-3140030857da.png)

**Comment by runningzyp** [comment]
感谢 @Lucareful
